language: node_js

node_js:
   - "8" # currently is the highest version supported by yarn

install:
  - npm install -g yarn
  - yarn global add @angular/cli
  - yarn global add karma
  - yarn install # make use of yarn.lock

before_script:
  - ng -v

script:
  - yarn lint
  - yarn test-cover

after_success:
  - yarn coveralls

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change
